sudo: false
language: python
python:
- '3.4'
install:
- pip install -r requirements_for_test.txt
script:
- ./scripts/run_tests.sh
env:
  secure: tgeumbN2oayp1twu3iVuuo5eMz/XVO303A2wdnR6bFMCfLCA7SVeKvDZ21ZpSh+J7tu8/9MQD2ATo95qyO9oraSg09BQ7UoEtpyrrcP21UBcNMbIsAdmOUAostlvg4hy1ZuSjytpzLDMZfS0QCjWPtZiXKW3XzmHHJyIdatcHsO3Jpi1vPRP11cZHd1SKwd1POYXDuX3Y9e68yt0P7Wr1/3mZ8u0XHtSg++SnZ0qDDwnWIsHqkcxr7R/n1MYvyUD8XPB+guqEq/7G6ipR+QrHN0fCVGXFksXGLSMSBg9sGQ1Mr+2yiOXL+4EmCfpx9VofmEOFDTdK70lFFn1sOG/GmceW4JT2Y2vLG+6vSJTmaHxeZmpYoKRa1EJJqyEpvjRM3A8lV993qIdAEBIE8s0w+DhkmXXCI3chSDT+2B/SlFbGw7G7E4hto/3FUrk7N7w+c5WaOQSqz4ZxTX4iIg9T7Bxo3s8l+UYYw4NfzEreRieEiFo58FgYrghEOvMp9PZ3tN3u2H+2yISE0C/+MSFUB2CWgFiTTD2XtWuQJgGNxyTYD1sbHaYT1EeDoz8JbhsACvIxpQdycVibHjP4hvP32nFFaznNpCm1ArS+vDtzR6Psx2vYb/u0rf1QoipVE/GPzqB9bwGHZ/0Cpsqy4KxYM74MOu3Gi3KCYzKGq7hRGI=
after_success:
- ./scripts/trigger-dependent-build.sh
notifications:
  slack:
    rooms:
      secure: vCmpAjdXkprqGzSnQzcco1lNiFuj/nRQdlVTGSnvg2HEqZUM5vzmWtQYw3WNS/bcgbVxV/nLgza17cdsmFqOuaZll4kDM0swnmk17eynImAHPFF/flGsNcw4oRV7WzWrq7j1TvGzJzxJkHYOjJFk0iMLM7+P76sWHI6Oa5NHQYH2l7a4hqzqmuUKaloHeZX/Ro2RmFE+/t/SfNr0pmtTRO4CfLfPUdUs9D8Mx0cyc1Z9Ke4Cq+R2Lsp8BwH0nye6pb9cI4h1YmUY/Xt8O1Z0QbncHZviWojSB2vV0V5WQPzqjjseAznJ1depK/LPOlRHlqddkEbGK28rDwsxbzY1q3DCZZiZZTXBD80HyNr/J4rfRAXhoCafwR57cqqIQ7G/fb5A/ckUM8TFKqUPh7wvu67OAiSWJmO78C8fumF3HxcoGp7DQOQPFLtWGuCfh2zjI9WbUhiHQwWl9/9qpgMEuXH7LOJAzgQbEp1A7XRmT2GupYEkGdFMwT8ojp8OXds08diEy1FNonWAtFZs8pO92urK862pCRB8WRQZWMjpcnif1Ht4QtwYFO9iVp5ygReTEoFuiQPMAypCVCzKgHe/W8LX55xzSnlUQqDU2NzN37LfC4ctS1h3BfIIU5KP9PmdgkKRUWcrFE3eMXPG36OdU4hRj4FMURzmAOZYhaSXuP8=
deploy:
- provider: s3
  access_key_id: AKIAI37IS2VAC5PJHHDA
  secret_access_key: &1
    secure: Ztj8D7S7YQAarbdF7T0XFRNDTzop/vrPdZL5e07L7c5TwXqr3Dy2ZcKDZMCDTkjgsx7cVu5OhtRtG/+k2FbfQqDrvyYI6jssSIokTdWdXLVdbtI4BqgEcoxouLgOIgAdqV1BzqfDVPiu9GUIlDIT1f/VjU3sRQGw5ioWXvwYkdzuqI+bXir8/Y1Vzcupqn7BoP2iyhB3FZ4HxHUjqau1g2g++17jfFgIghg6zaAuLWB3raGjWo6H+BvieZqIma0p643rs39fXjr8lIfvP8FGlKSTXzQX2+KGSjdTJx64KRSdO9iFuiedL1dkSbEXNebh2Q9M1FDdWmrO6PsgRFtQI0Kgy/3CATqlEEOjgPjBSyDIfzPGE+HBDyTId1hy2u/0BekDQRfJeCikV8ebcWRTjyr+j2EvUhhmDDQrZusyz25UA7IuurVEPVT/mzAEFseu4dMcKTlmk4Jo8eFqcrtyLcFpH7QPCwwIj7MjUlzwepvgxuhGR/UHIMDH7R8QLVuT3beE+AyumyJb0QHt4yLlg6WHxaK5ayNQBVm20yD64dRKQsEMvdewVz9fLhoa4sV5PNqBn0yghdiKnQA2XynBen8hEbpuraN/wvX9z+STMoR/fG33X2XwAn3f08qO1RzMy4mxsq75tkD8yR8i/JAMtawARuBzSk3asXol/EtwlbQ=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: alphagov/notifications-api
  bucket: notifications-api-codedeploy
- provider: codedeploy
  access_key_id: AKIAI37IS2VAC5PJHHDA
  secret_access_key: *1
  bucket: notifications-api-codedeploy
  key: notifications-api.zip
  bundle_type: zip
  application: notifications-api
  deployment_group: notifications_admin_deployment_group
  on: *2
before_deploy:
- zip -r notifications-api *
- mkdir -p dpl_cd_upload
- mv notifications-api.zip dpl_cd_upload/notifications-api.zip
